# Generated by Django 3.2.12 on 2022-09-27 12:51

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('article_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Add image to the article')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Name')),
                ('comment_content', models.CharField(max_length=200, verbose_name='comment')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_takencourse_completed', models.FloatField(default=0)),
                ('score', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_courses', to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=25)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('duration', models.FloatField(default=0)),
                ('duration_str', models.CharField(max_length=25)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='article.article', verbose_name='Article')),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='TakenCourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed_video', models.BooleanField(default=False)),
                ('takencourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.takencourse')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.video')),
            ],
        ),
    ]
