# Generated by Django 3.2.12 on 2022-09-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takencourse',
            options={'ordering': ['score']},
        ),
    ]
