# Generated by Django 3.2.12 on 2022-09-29 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_takencourse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
