# Generated by Django 3.2.12 on 2022-09-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_takencourse_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takencourse',
            options={'ordering': ['added']},
        ),
    ]
