# Generated by Django 3.2.12 on 2022-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['added']},
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
