# Generated by Django 3.2.12 on 2022-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20220923_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
    ]
