# Generated by Django 3.2.12 on 2022-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration_str',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
