# Generated by Django 3.2.12 on 2022-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_video_duration_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_str',
            field=models.CharField(max_length=25),
        ),
    ]
