# Generated by Django 3.2.12 on 2022-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_video_duration_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_completed_video',
            field=models.BooleanField(default=False),
        ),
    ]
