# Generated by Django 3.2.12 on 2022-09-07 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_options_alter_comment_options'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='article',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='article.article', verbose_name='Article'),
            preserve_default=False,
        ),
    ]
